[[section]]
title = "Allgemeines"
[[section.link]]
desc = "Digicampus (Meine Veranstaltungen)"
source = "/dc"
target = "https://digicampus.uni-augsburg.de/dispatch.php/my_courses"

[[section.link]]
desc = "Moodle"
source = "/moodle"
target = "https://moodle.uni-augsburg.de/"

[[section.link]]
desc = "STUDIS"
source = "/studis"
target = "https://studiswebstud.zv.uni-augsburg.de/FN2AUTH/FN2AuthServlet?op=Login&nologout=true"

[[section.link]]
desc = "VIBS"
source = "/vibs"
target = "https://vibs.uni-augsburg.de"

[[section.link]]
desc = "Fachschaft Informatik"
source = "/fs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/studierendenvertretung-informatik"

[[section.link]]
desc = "Fachschaft Mathematik"
source = "/fsmath"
target = "https://www.uni-augsburg.de/de/fakultaet/mntf/math/fachschaft/"

[[section.link]]
desc = "Klausurtermine"
source = "/klausurtermine"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studium/klausurtermine-informatik/"

[[section.link]]
desc = "Altklausuren"
source = "/altklausuren"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/studierendenvertretung-informatik/altklausuren/"

[[section.link]]
desc = "Mensa"
source = "/mensa"
target = "https://www.uni-augsburg.de/de/services/mensa/"

[[section.link]]
desc = "Hochschulsport"
source = "/sport"
target = "https://anmeldung.sport.uni-augsburg.de/angebote/aktueller_zeitraum/"

[[section.link]]
desc = "Mathe-Info Discord"
source = "/discord"
target = "https://discord.gg/SRYedBz"

[[section.link]]
desc = "Informationen zur Rückmeldung"
source = "/rueckmeldung"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/organisation-und-formales/rueckmeldung/"

[[section.link]]
desc = "Stundenpläne, Lehrveranstaltungen und Module"
source = "/lehrveranstaltungen"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studium/lehre/"


[[section]]
title = "1. Semester"
[[section.link]]
desc = "Informationen für Erstsemester"
source = "/ersti"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/"

[[section.link]]
desc = "Informationen zu Vor-/Brückenkursen"
source = "/vorkurs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/vorkurs/"

[[section.link]]
desc = "Informatik 1"
source = "/info1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=2988419e828a668210c8dc1fea784426"

[[section.link]]
desc = "Programmierkurs"
source = "/prog"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=932d5a277ae2263140aaed797aa08dce"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=3c0108874173b54b7d38a7278db393c6"

[[section.link]]
desc = "Mathematik für Informatik I"
source = "/mfi1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=5f04eb41d5e265b551e2da02716f2a1a"

[[section.link]]
desc = "Diskrete Strukturen und Logik"
source = "/dislo"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=263c7bc216f2df3d5e42da5051d5c0fc"

[[section.link]]
desc = "Lineare Algebra I"
source = "/la1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=f7ff6840f1414ab18c790d24a4c63be4"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=7a6962baafd363f26786ee5fd6b01813"


[[section]]
title = "2. Semester"
[[section.link]]
desc = "Informatik 2"
source = "/info2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=6c8ca5f01e6f82b4a9936b28307bdf07"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e48ce3c01e6fdc46665ef324116ee4fb"

[[section.link]]
desc = "Mathematik für Informatik II"
source = "/mfi2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=543cc909fe155e0537addaa5736fb230"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=4edb5ac81536bc53949739f602db15a5"

[[section.link]]
desc = "Einführung in die Theoretische Informatik"
source = "/ti"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=7a9f2f0c04415d6ab715ae095712abcd"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=9c00aff4376e6e6cf7b93f315b7c56d0"

[[section.link]]
desc = "Analysis I"
source = "/ana1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=ad94e9ef8548e008b04940e8c3c43eaf"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=690daad9e621b341cf5695479ff13191"


[[section]]
title = "3. Semester"
[[section.link]]
desc = "Informatik 3"
source = "/info3"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=afc80b81cb7b209d980c064b297cdc95"

[[section.link]]
desc = "Stochastik für Informatiker"
source = "/sfi"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=0612d9ccd069841760f8ad4dc0a3e792"

[[section.link]]
desc = "Datenbanksysteme"
source = "/dbs"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=62538e78a2218d51f32cd602d3caac05"


[[section]]
title = "4. Semester"
[[section.link]]
desc = "Systemnahe Informatik"
source = "/si"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=1ca79ae3f36b69fda8ee99c1091aeea5"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=dcface4ecfa9134ee078fe852591cb49"

[[section.link]]
desc = "Softwareprojekt"
source = "/sopro"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=697e1aebb1dac080e991865b9de854f4"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=17d0d4d40882454657836b4999bb1dd7"

[[section.link]]
desc = "Grundlagen der Human-Computer-Interaction / Multimedia Grundlagen II"
source = "/ghci"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details/?sem_id=c6f60fe57cec2378bdcb24c3b03728ce"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=22de509345a969f74ea16ce65a448476"


[[section]]
title = "5. Semester"
[[section.link]]
desc = "Kommunikationssysteme"
source = "/kommsys"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=cbf293b1a3d5cbc355793637eb8cb636"

[[section.link]]
desc = "Softwaretechnik"
source = "/swt"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=38a22e58a1ca4310f1a7c769cd014291"

[[section.link]]
desc = "Grundlagen der Signalverarbeitung und des maschinellen Lernens / Multimedia Grundlagen I"
source = "/svml"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e370aac8c8e376224329910408916987"


[[section]]
title = "Wahlbereich"

[[section]]
title = "Modulhandbuch"
[[section.link]]
desc = "Informatik"
source = "/mhb-inf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/54b19e6523e84fa76fa475a5fcbaaf59"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/mhb-infmm"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/b5a88d8f5d2287c2332017de25810874"

[[section.link]]
desc = "Medizinische Informatik"
source = "/mhb-medinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/ce47d910e566de921fa532a03033dd37"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/mhb-inginf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3a1f1abdcdee77f9779b2bcc0464579b"

[[section.link]]
desc = "Geoinformatik"
source = "/mhb-geoinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/f3627155bcec808eb33a4079294fab5f"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/mhb-win"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/7e443f73fa6b7a628f6c04d31b41e8a1"


[[section]]
title = "Prüfungsordnung"
[[section.link]]
desc = "Informatik"
source = "/po-inf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik/"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/po-infmm"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik-und-multimedia/"

[[section.link]]
desc = "Medizinische Informatik"
source = "/po-medinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-medizinische-informatik/"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/po-inginf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-ingenieurinformatik/"

[[section.link]]
desc = "Geoinformatik"
source = "/po-geoinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-geoinformatik/"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/po-win"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-wirtschaftsinformatik/"


