[[section]]
title = "Allgemeines"
[[section.link]]
desc = "Digicampus (Meine Veranstaltungen)"
source = "/dc"
target = "https://digicampus.uni-augsburg.de/dispatch.php/my_courses"

[[section.link]]
desc = "Moodle"
source = "/moodle"
target = "https://moodle.uni-augsburg.de/"

[[section.link]]
desc = "STUDIS"
source = "/studis"
target = "https://studiswebstud.zv.uni-augsburg.de/FN2AUTH/FN2AuthServlet?op=Login&nologout=true"

[[section.link]]
desc = "VIBS"
source = "/vibs"
target = "https://vibs.uni-augsburg.de"

[[section.link]]
desc = "eduroam"
source = "/eduroam"
target = "https://confluence.rz.uni-augsburg.de/display/RZSER/Nutzung+von+eduroam#Nutzungvoneduroam-HiergehteszudenAnleitungenf%C3%BCrdieverschiedenenBetriebssysteme:"

[[section.link]]
desc = "Fachschaft Informatik"
source = "/fs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/studierendenvertretung-informatik"

[[section.link]]
desc = "Fachschaft Mathematik"
source = "/fsmath"
target = "https://www.uni-augsburg.de/de/fakultaet/mntf/math/fachschaft/"

[[section.link]]
desc = "Klausurtermine"
source = "/klausurtermine"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studium/klausurtermine-informatik/"

[[section.link]]
desc = "Altklausuren"
source = "/altklausuren"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/studierendenvertretung-informatik/altklausuren/"

[[section.link]]
desc = "Prüfungsamt"
source = "/pruefungsamt"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/pruefungen/infos-und-antrage/fakultat-fur-angewandte-informatik-pruefungen/"

[[section.link]]
desc = "Mensa"
source = "/mensa"
target = "https://studentenwerk.online/hg-oeffnungszeiten"

[[section.link]]
desc = "Universitätsbibliothek"
source = "/bib"
target = "https://www.uni-augsburg.de/de/organisation/bibliothek/"

[[section.link]]
desc = "OPAC"
source = "/opac"
target = "https://opac.bibliothek.uni-augsburg.de/"

[[section.link]]
desc = "Hochschulsport"
source = "/sport"
target = "https://anmeldung.sport.uni-augsburg.de/angebote/aktueller_zeitraum/"

[[section.link]]
desc = "Mathe-Info Discord"
source = "/discord"
target = "https://discord.gg/SRYedBz"

[[section.link]]
desc = "Informationen zur Rückmeldung"
source = "/rueckmeldung"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/organisation-und-formales/rueckmeldung/"

[[section.link]]
desc = "Stundenpläne, Lehrveranstaltungen und Module"
source = "/lehrveranstaltungen"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studium/lehre/"

[[section.link]]
desc = "Beratungsangebote"
source = "/beratung"
target = "https://www.uni-augsburg.de/de/studium/organisation-beratung/beratung/"


[[section]]
title = "1. Semester"
[[section.link]]
desc = "Informationen für Erstsemester"
source = "/ersti"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/"

[[section.link]]
desc = "Informationen zu Vor-/Brückenkursen"
source = "/vorkurs"
target = "https://www.uni-augsburg.de/de/fakultaet/fai/informatik/studienanfanger/vorkurs/"

[[section.link]]
desc = "Informatik 1"
source = "/info1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=512a515167861658b6b7b33960d058d4"

[[section.link]]
desc = "Programmierkurs"
source = "/prog"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=b8fe14331c0fda489a1c8a9781a2d4ef"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=3c0108874173b54b7d38a7278db393c6"

[[section.link]]
desc = "Mathematik für Informatik I"
source = "/mfi1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=14d11dc50c0052240fa68dc410f768e4"

[[section.link]]
desc = "Diskrete Strukturen und Logik"
source = "/dislo"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=0d974e3cfda7b536faed3d17f32c7d45"

[[section.link]]
desc = "Lineare Algebra I"
source = "/la1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=f77349eb56f840116c527f3b5a499508"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=7a6962baafd363f26786ee5fd6b01813"


[[section]]
title = "2. Semester"
[[section.link]]
desc = "Informatik 2"
source = "/info2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=b08e21d29409e4ddd61e15d381bbb8f7"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=e48ce3c01e6fdc46665ef324116ee4fb"

[[section.link]]
desc = "Mathematik für Informatik II"
source = "/mfi2"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=75de1b4b62256025ed1be9761e561785"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=4edb5ac81536bc53949739f602db15a5"

[[section.link]]
desc = "Einführung in die Theoretische Informatik"
source = "/ti"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=6d78e28c022e11305adea13838a2a0f8"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=9c00aff4376e6e6cf7b93f315b7c56d0"

[[section.link]]
desc = "Analysis I"
source = "/ana1"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=23a7c955faa7b1b65ea0c8e990c6cbe2"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=690daad9e621b341cf5695479ff13191"


[[section]]
title = "3. Semester"
[[section.link]]
desc = "Informatik 3"
source = "/info3"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=584bdddf75c0a6b7bb57d32c1bd781d1"

[[section.link]]
desc = "Stochastik für Informatiker"
source = "/sfi"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=7647effa4556cb2c0cd15660b7d524c3"

[[section.link]]
desc = "Datenbanksysteme"
source = "/dbs"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=6b2105e71c11c81c7d56564e4e3e44e8"


[[section]]
title = "4. Semester"
[[section.link]]
desc = "Systemnahe Informatik"
source = "/si"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=b1ceec6bf508d7bae84679fe9f038e84"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=dcface4ecfa9134ee078fe852591cb49"

[[section.link]]
desc = "Softwareprojekt"
source = "/sopro"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=ea34f74a22492ed252e8b0d4e9a3c521"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=17d0d4d40882454657836b4999bb1dd7"

[[section.link]]
desc = "Grundlagen der Human-Computer-Interaction / Multimedia Grundlagen II"
source = "/ghci"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=400900123675975df97c8303d748c980"
link = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=22de509345a969f74ea16ce65a448476"


[[section]]
title = "5. Semester"
[[section.link]]
desc = "Kommunikationssysteme"
source = "/kommsys"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=920442792e8c45155dfec2954a48903f"

[[section.link]]
desc = "Softwaretechnik"
source = "/swt"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=904919b45bd1728967c1916b7e286ca6"

[[section.link]]
desc = "Grundlagen der Signalverarbeitung und des maschinellen Lernens / Multimedia Grundlagen I"
source = "/svml"
target = "https://digicampus.uni-augsburg.de/dispatch.php/course/details?sem_id=6059244ef1ed9d091408a592513e1249"


[[section]]
title = "Wahlbereich"

[[section]]
title = "Modulhandbuch"
[[section.link]]
desc = "Informatik"
source = "/mhb-inf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/54b19e6523e84fa76fa475a5fcbaaf59"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/mhb-infmm"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/b5a88d8f5d2287c2332017de25810874"

[[section.link]]
desc = "Medizinische Informatik"
source = "/mhb-medinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/ce47d910e566de921fa532a03033dd37"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/mhb-inginf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/3a1f1abdcdee77f9779b2bcc0464579b"

[[section.link]]
desc = "Geoinformatik"
source = "/mhb-geoinf"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/f3627155bcec808eb33a4079294fab5f"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/mhb-win"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/7e443f73fa6b7a628f6c04d31b41e8a1"

[[section.link]]
desc = "Data Science"
source = "/mhb-ds"
target = "https://digicampus.uni-augsburg.de/dispatch.php/search/angebot/studiengang/e47cb6edabf5ef9fce82b6369b5ee598"


[[section]]
title = "Prüfungsordnung"
[[section.link]]
desc = "Informatik"
source = "/po-inf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik/"

[[section.link]]
desc = "Informatik und Multimedia"
source = "/po-infmm"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-informatik-und-multimedia/"

[[section.link]]
desc = "Medizinische Informatik"
source = "/po-medinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-medizinische-informatik/"

[[section.link]]
desc = "Ingenieurinformatik"
source = "/po-inginf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-ingenieurinformatik/"

[[section.link]]
desc = "Geoinformatik"
source = "/po-geoinf"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-geoinformatik/"

[[section.link]]
desc = "Wirtschaftsinformatik"
source = "/po-win"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/fai-bachelor-wirtschaftsinformatik/"

[[section.link]]
desc = "Data Science"
source = "/po-ds"
target = "https://www.uni-augsburg.de/de/services/rechtssammlung/BScDataSc/"

[[section]]
title = "Klokurier"
[[section.link]]
desc = "Erstiheft Informatik"
source = "/erstiheft"
target = "https://megastore.rz.uni-augsburg.de/get/S5z6Qnd9hT/"

[[section.link]]
desc = "Kneipentour Anmeldung"
source = "/kneip"
target = "https://docs.google.com/forms/d/e/1FAIpQLSdl49Jky-DgLUZ8LihTScW8UPUYQ1O3kyMw7vVq4m-CvSFnfg/viewform"
